[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_regressions"
path = "src/lib.rs"

[dependencies]
plotly = "*"
nalgebra = "*"
smartcore = "*"
rand = "*"
